apiVersion: batch/v1
kind: Job
metadata:
  name: attack-simulator
spec:
  template:
    spec:
      containers:
      - name: simulator
        image: attack-simulator
        imagePullPolicy: IfNotPresent  # For local testing
      restartPolicy: Never
  backoffLimit: 0
